# Generated by Django 2.2.7 on 2019-12-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodical',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4)),
                ('volume', models.IntegerField()),
                ('issue', models.IntegerField()),
                ('sum', models.IntegerField()),
                ('residue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicalIndex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issn', models.CharField(max_length=9, unique=True)),
                ('name', models.CharField(max_length=16)),
                ('postsign', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(default='admin', max_length=15, primary_key=True, serialize=False)),
                ('user_password', models.CharField(default='123456', max_length=30)),
                ('user_email', models.CharField(default='', max_length=30)),
                ('isadmin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('issn', models.ForeignKey(on_delete='CASCADE', to='managesystem.PeriodicalIndex', to_field='issn')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicalInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_name', models.CharField(max_length=50)),
                ('first_author', models.CharField(max_length=8)),
                ('second_author', models.CharField(blank=True, max_length=8)),
                ('third_author', models.CharField(blank=True, max_length=8)),
                ('forth_author', models.CharField(blank=True, max_length=8)),
                ('first_keyword', models.CharField(blank=True, max_length=14)),
                ('second_keyword', models.CharField(blank=True, max_length=14)),
                ('third_keyword', models.CharField(blank=True, max_length=14)),
                ('forth_keyword', models.CharField(blank=True, max_length=14)),
                ('fifth_keyword', models.CharField(blank=True, max_length=14)),
                ('page', models.IntegerField()),
                ('book_id', models.ForeignKey(on_delete='CASCADE', to='managesystem.Periodical')),
            ],
        ),
        migrations.AddField(
            model_name='periodical',
            name='issn',
            field=models.ForeignKey(on_delete='CASCADE', to='managesystem.PeriodicalIndex', to_field='issn'),
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('borrow_date', models.DateTimeField()),
                ('back_date', models.DateTimeField()),
                ('book_id', models.ForeignKey(on_delete='CSCADE', to='managesystem.Periodical')),
                ('user_name', models.ForeignKey(on_delete='CSCADE', to='managesystem.User')),
            ],
        ),
    ]
