# Generated by Django 2.2.7 on 2019-12-03 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managesystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='User',
        ),
    ]
