# Generated by Django 2.2.7 on 2019-12-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managesystem', '0002_auto_20191228_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
