# Generated by Django 2.2.7 on 2019-12-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managesystem', '0002_auto_20191203_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodical',
            fields=[
                ('book_sign', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4)),
                ('volume', models.IntegerField()),
                ('issue', models.IntegerField()),
                ('sum', models.IntegerField()),
                ('residue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicalIndex',
            fields=[
                ('issn', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('sign', models.CharField(max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='admin', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(default='123456', max_length=30),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_sign', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('issn', models.ForeignKey(on_delete='CASCADE', to='managesystem.PeriodicalIndex')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicalInfo',
            fields=[
                ('paper_sign', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('paper_name', models.CharField(max_length=50)),
                ('first_author', models.CharField(max_length=8)),
                ('second_author', models.CharField(blank=True, max_length=8)),
                ('third_author', models.CharField(blank=True, max_length=8)),
                ('forth_author', models.CharField(blank=True, max_length=8)),
                ('first_keyword', models.CharField(blank=True, max_length=14)),
                ('second_keyword', models.CharField(blank=True, max_length=14)),
                ('third_keyword', models.CharField(blank=True, max_length=14)),
                ('forth_keyword', models.CharField(blank=True, max_length=14)),
                ('fifth_keyword', models.CharField(blank=True, max_length=14)),
                ('page', models.IntegerField()),
                ('book_sign', models.ForeignKey(on_delete='CASCADE', to='managesystem.Periodical')),
            ],
        ),
        migrations.AddField(
            model_name='periodical',
            name='issn',
            field=models.ForeignKey(on_delete='CASCADE', to='managesystem.PeriodicalIndex'),
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('borrow_sign', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('borrow_date', models.DateTimeField()),
                ('back_date', models.DateTimeField()),
                ('book_sign', models.ForeignKey(on_delete='CSCADE', to='managesystem.Periodical')),
                ('user_name', models.ForeignKey(on_delete='CSCADE', to='managesystem.User')),
            ],
        ),
    ]
