# Generated by Django 2.2.7 on 2019-12-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managesystem', '0003_auto_20191228_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
