# Generated by Django 2.2.7 on 2019-12-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managesystem', '0004_auto_20191228_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='year',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
